In [6]:
#@title { vertical-output: true}
!git clone https://github.com/maxwell-petitjean/fpl_26.git
%cd fpl_26
!pip install -q -r requirements.txt

Cloning into 'fpl_26'...
remote: Enumerating objects: 113, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 113 (delta 36), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (113/113), 6.60 MiB | 5.21 MiB/s, done.
Resolving deltas: 100% (36/36), done.
/content/fpl_26/fpl_26
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 34.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 54.5 MB/s eta 0:00:00

In [5]:
#@title { vertical-output: true}
import pandas as pd
from pathlib import Path

HISTORIC_PATH = Path("data/raw/historic")

seasons = sorted([
    p.name
    for p in HISTORIC_PATH.iterdir()
    if p.is_dir()
])

print("Seasons:", seasons)

Seasons: ['2021-22', '2022-23', '2023-24', '2024-25', '2025-26']

In [7]:
#@title { vertical-output: true }

frames = []

for season in seasons:
    path = HISTORIC_PATH / season / "players_raw.csv"

    df = pd.read_csv(path, low_memory=False)

    keep = [
        c for c in [
            "id",
            "code",
            "opta_code",
            "first_name",
            "second_name",
            "web_name",
            "team",
            "element_type"
        ]
        if c in df.columns
    ]

    df = df[keep].copy()
    df["season"] = season

    df = df.rename(columns={
        "id": "fpl_element_id",
        "code": "player_code",
        "team": "team_id",
        "element_type": "position_id"
    })

    frames.append(df)

players = pd.concat(frames, ignore_index=True)

print(f"Rows: {len(players):,}")
print(f"Unique player codes: {players['player_code'].nunique():,}")
players.head()

Rows: 4,025
Unique player codes: 1,797

,fpl_element_id,player_code,first_name,second_name,web_name,team_id,position_id,season,opta_code
0,1,80201,Bernd,Leno,Leno,1,1,2021-22,NaN
1,2,115918,Rúnar Alex,Rúnarsson,Rúnarsson,1,1,2021-22,NaN
2,3,47431,Willian,Borges Da Silva,Willian,1,3,2021-22,NaN
3,4,54694,Pierre-Emerick,Aubameyang,Aubameyang,1,4,2021-22,NaN
4,5,58822,Cédric,Soares,Cédric,1,2,2021-22,NaN

In [8]:
#@title { vertical-output: true }
# --------------------------------------------------
# CHECK 1: missing player codes
# --------------------------------------------------

missing = players[players["player_code"].isna()]

print("\n=== MISSING PLAYER CODES ===")
print(f"Rows: {len(missing):,}")

display(missing.head(20))


# --------------------------------------------------
# CHECK 2: duplicate code within the SAME season
# --------------------------------------------------

duplicates = (
    players
    .groupby(["season", "player_code"])
    .size()
    .reset_index(name="rows")
    .query("rows > 1")
)

print("\n=== DUPLICATE CODE WITHIN SEASON ===")
print(f"Cases: {len(duplicates):,}")

display(duplicates.head(20))


# --------------------------------------------------
# CHECK 3: names associated with each code
# --------------------------------------------------

name_check = (
    players
    .groupby("player_code")
    .agg(
        seasons=("season", "nunique"),
        names=("web_name", lambda x: sorted(set(x.dropna()))),
        first_names=("first_name", lambda x: sorted(set(x.dropna()))),
        second_names=("second_name", lambda x: sorted(set(x.dropna())))
    )
    .reset_index()
)

name_check["web_name_count"] = name_check["names"].apply(len)
name_check["second_name_count"] = name_check["second_names"].apply(len)

name_changes = (
    name_check[
        (name_check["web_name_count"] > 1) |
        (name_check["second_name_count"] > 1)
    ]
    .sort_values(
        ["second_name_count", "web_name_count"],
        ascending=False
    )
)

print("\n=== CODES WITH NAME CHANGES ===")
print(f"Cases: {len(name_changes):,}")

display(name_changes.head(50))


# --------------------------------------------------
# CHECK 4: players appearing across multiple seasons
# --------------------------------------------------

multi_season = (
    name_check[name_check["seasons"] > 1]
    .sort_values("seasons", ascending=False)
)

print("\n=== CROSS-SEASON PLAYERS ===")
print(f"Players: {len(multi_season):,}")

display(multi_season.head(50))


# --------------------------------------------------
# CHECK 5: team / position changes
# --------------------------------------------------

career_changes = (
    players
    .groupby("player_code")
    .agg(
        seasons=("season", "nunique"),
        teams=("team_id", "nunique"),
        positions=("position_id", "nunique")
    )
    .reset_index()
)

print("\n=== TEAM CHANGES ===")
display(
    career_changes[
        career_changes["teams"] > 1
    ].sort_values("teams", ascending=False).head(30)
)

print("\n=== POSITION CHANGES ===")
display(
    career_changes[
        career_changes["positions"] > 1
    ].sort_values("positions", ascending=False).head(30)
)

=== MISSING PLAYER CODES ===
Rows: 0

Empty DataFrame
Columns: [fpl_element_id, player_code, first_name, second_name, web_name, team_id, position_id, season, opta_code]
Index: []

=== DUPLICATE CODE WITHIN SEASON ===
Cases: 0

Empty DataFrame
Columns: [season, player_code, rows]
Index: []

=== CODES WITH NAME CHANGES ===
Cases: 197

,player_code,seasons,names,first_names,second_names,web_name_count,second_name_count
534,194634,4,"[Diogo J., Diogo Jota, Jota]",[Diogo],"[Jota, Teixeira da Silva]",3,2
1195,481624,4,"[Jaden, Philogene, Philogene-Bidace]",[Jaden],"[Philogene, Philogene-Bidace]",3,2
38,40349,3,"[Begovic, Begović]",[Asmir],"[Begovic, Begović]",2,2
74,51940,2,"[De Gea, de Gea]",[David],"[De Gea Quintana, de Gea]",2,2
107,59859,4,"[Gündogan, Gündoğan]","[Ilkay, İlkay]","[Gündogan, Gündoğan]",2,2
131,67089,5,"[Dubravka, Dúbravka]",[Martin],"[Dubravka, Dúbravka]",2,2
213,91651,5,"[Kovacic, Kovačić]",[Mateo],"[Kovacic, Kovačić]",2,2
217,92371,2,"[Marí, Pablo Marí]",[Pablo],"[Marí, Marí Villar]",2,2
235,98980,5,"[Martinez, Martínez]",[Emiliano],"[Martínez, Martínez Romero]",2,2
246,102057,5,"[Jiménez, Raúl]",[Raúl],"[Jiménez, Jiménez Rodríguez]",2,2
310,116535,5,"[A.Becker, Alisson]",[Alisson],"[Becker, Ramses Becker]",2,2
321,121145,4,"[Cancelo, João Cancelo]","[João, João Pedro Cavaco]","[Cancelo, Cavaco Cancelo]",2,2
370,153256,3,"[Elneny, M.Elneny]","[Mohamed, Mohamed Naser]","[El Sayed Elneny, Elneny]",2,2
378,154296,3,"[J.Palhinha, Palhinha]","[João, João Maria]","[Lobo Alves Palhares Costa Palhinha Gonçalves,...",2,2
396,156689,5,"[Andreas, Pereira]",[Andreas],"[Hoelgebaum Pereira, Pereira]",2,2
405,159533,5,"[Adama, Traoré]",[Adama],"[Traoré, Traoré Diarra]",2,2
452,171314,5,"[Dias, Rúben]","[Rúben, Rúben Santos]","[Gato Alves Dias, dos Santos Gato Alves Dias]",2,2
499,180151,3,"[Vlasic, Vlašić]",[Nikola],"[Vlasic, Vlašić]",2,2
516,184754,5,"[Hee Chan, Hwang]","[Hee-Chan, Hwang]","[Hee-chan, Hwang]",2,2
559,199670,5,"[Edouard, Édouard]",[Odsonne],"[Edouard, Édouard]",2,2
588,204214,4,"[Estupiñan, Estupiñán]",[Pervis],"[Estupiñán, Estupiñán Tenorio]",2,2
601,205651,5,"[G.Jesus, Jesus]","[Gabriel, Gabriel Fernando]","[Fernando de Jesus, de Jesus]",2,2
634,212314,4,"[Lukic, Lukić]","[Sasa, Saša]","[Lukic, Lukić]",2,2
652,215059,5,"[Sanchez, Sánchez]",[Robert],"[Lynch Sánchez, Sánchez]",2,2
656,215439,5,"[Soucek, Souček]","[Tomas, Tomáš]","[Soucek, Souček]",2,2
674,217593,3,"[Fornals, P.Fornals]",[Pablo],"[Fornals, Fornals Malla]",2,2
697,220566,5,"[Rodri, Rodrigo]","[Rodrigo, Rodrigo 'Rodri']","[Hernandez, Hernandez Cascante]",2,2
720,222627,3,"[J.Virginia, Virgínia]",[João],"[Neves Virgínia, Virgínia]",2,2
835,242880,4,"[B.Badiashile, Badiashile]",[Benoît],"[Badiashile, Badiashile Mukinayi]",2,2
960,437748,2,"[M.Trésor, Trésor]",[Mike],"[Trésor, Trésor Ndayishimiye]",2,2
1034,448514,5,"[Ait Nouri, Aït-Nouri]",[Rayan],"[Ait Nouri, Aït-Nouri]",2,2
1042,449988,5,"[Fabio Silva, Fábio Silva]","[Fabio, Fábio]","[Silva, Soares Silva]",2,2
1056,451302,3,"[Altay, Bayindir]",[Altay],"[Bayindir, Bayındır]",2,2
1097,461584,2,"[Marcal, Marçal-Madivadua]",[Wanya],"[Marçal-Madivadua, Marçal-Madivádua]",2,2
1123,465390,3,"[Hayden, Kesler-Hayden]",[Kaine],"[Hayden, Kesler-Hayden]",2,2
1251,490721,5,"[Bueno, H.Bueno]",[Hugo],"[Bueno, Bueno López]",2,2
1282,493125,3,"[Dragusin, Drăgușin]",[Radu],"[Dragusin, Drăgușin]",2,2
1307,496208,4,"[Doak, Gannon-Doak]",[Ben],"[Doak, Gannon-Doak]",2,2
1314,496683,3,"[Kinsey, Kinsey-Wellings]",[Max],"[Kinsey, Kinsey-Wellings]",2,2
1366,508479,2,"[Jörgensen, Jørgensen]",[Filip],"[Jörgensen, Jørgensen]",2,2
1373,510500,2,"[Jota, Jota Silva]",[João Pedro],"[Ferreira Silva, Ferreira da Silva]",2,2
1391,514254,2,"[Gomez, Gómez]",[Diego],"[Gómez, Gómez Amarilla]",2,2
1407,515501,2,"[Fernandez, Álvaro Fernández]",[Álvaro],"[Fernández, Fernández Carreras]",2,2
1570,559962,2,"[Jimoh, Jimoh-Aloba]",[Jamaldeen],"[Jimoh, Jimoh-Aloba]",2,2
1595,570241,3,"[Ji-soo, Kim Ji-Soo]","[Ji-Soo, Kim]","[Ji-soo, Kim]",2,2
1664,593001,3,"[Gonzalez, González]",[Enso],"[González, González Medina]",2,2
1729,623095,2,"[Min-hyeok, Yang]","[Min-Hyeok, Yang]","[Min-hyeok, Yang]",2,2
28,37096,5,[Fabianski],"[Lukasz, Łukasz]","[Fabianski, Fabiański]",1,2
61,47431,4,[Willian],[Willian],"[Borges Da Silva, Borges da Silva]",1,2
104,58822,3,[Cédric],[Cédric],"[Alves Soares, Soares]",1,2

=== CROSS-SEASON PLAYERS ===
Players: 1,016

,player_code,seasons,names,first_names,second_names,web_name_count,second_name_count
1398,514356,5,[Lavia],"[Romeo, Roméo]",[Lavia],1,1
39,40383,5,[Forster],[Fraser],[Forster],1,1
28,37096,5,[Fabianski],"[Lukasz, Łukasz]","[Fabianski, Fabiański]",1,2
1371,510362,5,[Toti],"[Toti, Toti António]",[Gomes],1,1
1345,501837,5,[Mosquera],[Yerson],"[Mosquera, Mosquera Valdelamar]",1,2
1283,493250,5,"[Amad, Diallo]",[Amad],[Diallo],2,1
1280,493105,5,[Garnacho],[Alejandro],"[Garnacho, Garnacho Ferreyra]",1,2
1251,490721,5,"[Bueno, H.Bueno]",[Hugo],"[Bueno, Bueno López]",2,2
1245,490145,5,[Scarlett],[Dane],[Scarlett],1,1
1242,490094,5,[Iroegbunam],[Tim],[Iroegbunam],1,1
1229,487838,5,[Hall],[Lewis],[Hall],1,1
1220,487117,5,[Ferguson],[Evan],[Ferguson],1,1
1217,486672,5,[Caicedo],[Moisés],"[Caicedo, Caicedo Corozo]",1,2
1191,480455,5,[Branthwaite],[Jarrad],[Branthwaite],1,1
1114,463748,5,[Hein],[Karl],[Hein],1,1
1104,462424,5,[Saliba],[William],[Saliba],1,1
1101,462381,5,[Marschall],[Filip],[Marschall],1,1
68,50175,5,[Welbeck],[Danny],[Welbeck],1,1
66,49262,5,[Steele],[Jason],[Steele],1,1
1052,450542,5,"[J.Rak-Sakyi, Rak-Sakyi]",[Jesurun],[Rak-Sakyi],2,1
1042,449988,5,"[Fabio Silva, Fábio Silva]","[Fabio, Fábio]","[Silva, Soares Silva]",2,2
1039,449434,5,[Elanga],[Anthony],[Elanga],1,1
1034,448514,5,"[Ait Nouri, Aït-Nouri]",[Rayan],"[Ait Nouri, Aït-Nouri]",2,2
1014,446008,5,[Mbeumo],[Bryan],[Mbeumo],1,1
1009,445044,5,[Kulusevski],[Dejan],[Kulusevski],1,1
1008,444884,5,[Elliott],[Harvey],[Elliott],1,1
1005,444463,5,"[Fofana, W.Fofana]",[Wesley],[Fofana],2,1
1001,444145,5,[Martinelli],"[Gabriel, Gabriel Teodoro]",[Martinelli Silva],1,1
985,441192,5,[Sarmiento],[Jeremy],"[Sarmiento, Sarmiento Morante]",1,2
984,441191,5,[Livramento],[Tino],[Livramento],1,1
978,440323,5,[Broja],[Armando],[Broja],1,1
947,436234,5,[Bryan],[Bryan],[Gil Salvatierra],1,1
933,433154,5,[McNeil],[Dwight],[McNeil],1,1
108,59949,5,[Coleman],"[Seamus, Séamus]",[Coleman],1,1
101,58621,5,[Walker],[Kyle],[Walker],1,1
96,57328,5,[Clyne],[Nathaniel],[Clyne],1,1
927,432830,5,[Collins],[Nathan],[Collins],1,1
924,432714,5,[McAtee],[James],[McAtee],1,1
909,428580,5,[Onyeka],[Frank],[Onyeka],1,1
879,247632,5,[Neto],[Pedro],[Lomba Neto],1,1
860,244851,5,[Palmer],[Cole],[Palmer],1,1
857,244731,5,[Luis Díaz],[Luis],"[Díaz, Díaz Marulanda]",1,2
856,244723,5,[Mitchell],[Tyrick],[Mitchell],1,1
848,243571,5,[Patterson],[Nathan],[Patterson],1,1
839,243016,5,[Mac Allister],[Alexis],[Mac Allister],1,1
800,232826,5,[Gordon],[Anthony],[Gordon],1,1
798,232792,5,[Lamptey],[Tariq],[Lamptey],1,1
797,232787,5,[Gallagher],[Conor],[Gallagher],1,1
796,232653,5,"[J.Ramsey, Ramsey]",[Jacob],[Ramsey],2,1
131,67089,5,"[Dubravka, Dúbravka]",[Martin],"[Dubravka, Dúbravka]",2,2

=== TEAM CHANGES ===

      player_code  seasons  teams  positions
978        440323        5      5          1
839        243016        5      4          1
1110       463034        4      4          1
924        432714        5      4          1
652        215059        5      4          1
1398       514356        5      4          1
512        184349        5      4          2
405        159533        5      4          1
255        103955        4      4          1
619        209243        5      4          1
853        244619        4      4          1
1006       444765        4      4          1
239        101178        5      4          1
459        172649        5      4          1
709        221399        5      4          1
1220       487117        5      4          1
1217       486672        5      4          1
1352       503301        4      4          1
284        109646        4      4          1
1039       449434        5      4          1
4           15157        5      4          1
285        109745        5      4          1
860        244851        5      4          1
481        174874        5      4          1
590        204580        5      3          1
297        111931        3      3          1
981        440993        3      3          2
287        110735        5      3          1
304        114283        5      3          1
1242       490094        5      3          1

=== POSITION CHANGES ===

     player_code  seasons  teams  positions
82         55037        3      2          2
92         56983        3      2          2
158        80146        4      3          2
164        80954        2      2          2
198        87873        2      2          2
413       165153        4      2          2
447       170137        3      2          2
471       173818        2      2          2
482       174932        3      2          2
491       178186        5      1          2
503       180974        5      2          2
512       184349        5      4          2
516       184754        5      1          2
534       194634        4      2          2
558       199598        4      3          2
635       212319        5      2          2
640       213198        3      2          2
670       216646        5      3          2
686       219847        5      2          2
763       229164        2      2          2
787       232351        2      2          2
795       232620        2      2          2
838       242898        4      3          2
840       243298        4      2          2
892       248937        3      2          2
893       249231        4      2          2
908       428399        2      1          2
914       430871        4      2          2
957       437730        4      2          2
964       438234        2      1          2

In [9]:
#@title { vertical-output: true }
import re
import unicodedata

def normalise_name(value):
    if pd.isna(value):
        return ""

    value = str(value).lower().strip()

    # remove accents
    value = "".join(
        c for c in unicodedata.normalize("NFKD", value)
        if not unicodedata.combining(c)
    )

    # remove punctuation/spaces
    value = re.sub(r"[^a-z0-9]", "", value)

    return value


players["full_name"] = (
    players["first_name"].fillna("")
    + " "
    + players["second_name"].fillna("")
).str.strip()

players["full_name_normalised"] = (
    players["full_name"].apply(normalise_name)
)

normalised_name_check = (
    players
    .groupby("player_code")
    .agg(
        seasons=("season", "nunique"),
        names=("full_name", lambda x: sorted(set(x))),
        normalised_names=(
            "full_name_normalised",
            lambda x: sorted(set(x))
        )
    )
    .reset_index()
)

normalised_name_check["normalised_name_count"] = (
    normalised_name_check["normalised_names"].apply(len)
)

possible_reuse = (
    normalised_name_check[
        normalised_name_check["normalised_name_count"] > 1
    ]
    .sort_values("normalised_name_count", ascending=False)
)

print(
    f"Possible genuine name mismatches: "
    f"{len(possible_reuse):,}"
)

display(possible_reuse.head(50))

Possible genuine name mismatches: 129

,player_code,seasons,names,normalised_names,normalised_name_count
452,171314,5,"[Rúben Gato Alves Dias, Rúben Santos Gato Alve...","[rubendossantosgatoalvesdias, rubengatoalvesdi...",3
697,220566,5,"[Rodrigo 'Rodri' Hernandez, Rodrigo 'Rodri' He...","[rodrigohernandez, rodrigorodrihernandez, rodr...",3
321,121145,4,"[João Cancelo, João Cavaco Cancelo, João Pedro...","[joaocancelo, joaocavacocancelo, joaopedrocava...",3
28,37096,5,"[Lukasz Fabianski, Łukasz Fabiański]","[lukaszfabianski, ukaszfabianski]",2
74,51940,2,"[David De Gea Quintana, David de Gea]","[daviddegea, daviddegeaquintana]",2
191,85971,5,"[Heung-Min Son, Son Heung-min]","[heungminson, sonheungmin]",2
217,92371,2,"[Pablo Marí, Pablo Marí Villar]","[pablomari, pablomarivillar]",2
128,66749,3,"[Romelu Lukaku, Romelu Lukaku Bolingoli]","[romelulukaku, romelulukakubolingoli]",2
104,58822,3,"[Cédric Alves Soares, Cédric Soares]","[cedricalvessoares, cedricsoares]",2
261,106468,4,"[Alexandre Moreno Lopera, Álex Moreno Lopera]","[alexandremorenolopera, alexmorenolopera]",2
278,108823,3,"[Bamidele Alli, Dele Alli]","[bamidelealli, delealli]",2
280,109345,5,"[Solly March, Solomon March]","[sollymarch, solomonmarch]",2
282,109528,3,"[Javier Manquillo, Javier Manquillo Gaitán]","[javiermanquillo, javiermanquillogaitan]",2
285,109745,5,"[Kepa Arrizabalaga, Kepa Arrizabalaga Revuelta]","[kepaarrizabalaga, kepaarrizabalagarevuelta]",2
297,111931,3,"[Ricardo Barbosa Pereira, Ricardo Domingos Bar...","[ricardobarbosapereira, ricardodomingosbarbosa...",2
235,98980,5,"[Emiliano Martínez, Emiliano Martínez Romero]","[emilianomartinez, emilianomartinezromero]",2
163,80801,4,"[Idrissa Gana Gueye, Idrissa Gueye]","[idrissaganagueye, idrissagueye]",2
319,120250,3,"[André Filipe Tavares Gomes, André Tavares Gomes]","[andrefilipetavaresgomes, andretavaresgomes]",2
310,116535,5,"[Alisson Becker, Alisson Ramses Becker]","[alissonbecker, alissonramsesbecker]",2
365,152590,3,"[Alex Nicolao Telles, Alex Telles]","[alexnicolaotelles, alextelles]",2
351,141746,5,"[Bruno Borges Fernandes, Bruno Miguel Borges F...","[brunoborgesfernandes, brunomiguelborgesfernan...",2
378,154296,3,[João Maria Lobo Alves Palhares Costa Palhinha...,[joaomarialoboalvespalharescostapalhinhagoncal...,2
381,154566,4,"[Dominic Solanke, Dominic Solanke-Mitchell]","[dominicsolanke, dominicsolankemitchell]",2
396,156689,5,"[Andreas Hoelgebaum Pereira, Andreas Pereira]","[andreashoelgebaumpereira, andreaspereira]",2
370,153256,3,"[Mohamed Elneny, Mohamed Naser El Sayed Elneny]","[mohamedelneny, mohamednaserelsayedelneny]",2
403,158983,3,"[Endo Wataru, Wataru Endo]","[endowataru, wataruendo]",2
404,159506,3,"[Ola Aina, Olu Aina]","[olaaina, oluaina]",2
418,165809,5,"[Bernardo Mota Veiga de Carvalho e Silva, Bern...","[bernardomotaveigadecarvalhoesilva, bernardove...",2
405,159533,5,"[Adama Traoré, Adama Traoré Diarra]","[adamatraore, adamatraorediarra]",2
451,171287,5,"[Joe Gomez, Joseph Gomez]","[joegomez, josephgomez]",2
453,171317,2,"[Rúben Diogo da Silva Neves, Rúben da Silva Ne...","[rubendasilvaneves, rubendiogodasilvaneves]",2
463,172850,4,"[Ben Chilwell, Benjamin Chilwell]","[benchilwell, benjaminchilwell]",2
246,102057,5,"[Raúl Jiménez, Raúl Jiménez Rodríguez]","[rauljimenez, rauljimenezrodriguez]",2
482,174932,3,"[Sergi Canós, Sergi Canós Tenés]","[sergicanos, sergicanostenes]",2
493,179018,4,"[Miguel Almirón, Miguel Almirón Rejala]","[miguelalmiron, miguelalmironrejala]",2
506,183656,5,"[Josh Dasilva, Pelenda Joshua Dasilva]","[joshdasilva, pelendajoshuadasilva]",2
494,179268,5,"[Marc Cucurella, Marc Cucurella Saseta]","[marccucurella, marccucurellasaseta]",2
527,193204,2,"[Joe Aribo, Joe Ayodele-Aribo]","[joearibo, joeayodelearibo]",2
534,194634,4,"[Diogo Jota, Diogo Teixeira da Silva]","[diogojota, diogoteixeiradasilva]",2
536,195384,2,"[Mikel Merino, Mikel Merino Zazón]","[mikelmerino, mikelmerinozazon]",2
516,184754,5,"[Hee-Chan Hwang, Hwang Hee-chan]","[heechanhwang, hwangheechan]",2
553,198869,5,"[Ben White, Benjamin White]","[benjaminwhite, benwhite]",2
560,199796,5,"[Matthew Cash, Matty Cash]","[matthewcash, mattycash]",2
563,200089,5,"[Joe Willock, Joseph Willock]","[joewillock, josephwillock]",2
588,204214,4,"[Pervis Estupiñán, Pervis Estupiñán Tenorio]","[pervisestupinan, pervisestupinantenorio]",2
595,204814,2,"[Ben Brereton, Ben Brereton Díaz]","[benbrereton, benbreretondiaz]",2
600,205533,5,"[Eddie Nketiah, Edward Nketiah]","[eddienketiah, edwardnketiah]",2
621,209288,4,"[Thomas McGill, Tom McGill]","[thomasmcgill, tommcgill]",2
552,198849,2,"[Lucas Torreira, Lucas Torreira di Pascua]","[lucastorreira, lucastorreiradipascua]",2
638,212721,2,"[Lyanco Evangelista Silveira Neves Vojnovic, L...","[lyancoevangelistasilveiranevesvojnovic, lyanc...",2

In [ ]:
#@title { vertical-output: true }

In [ ]:
#@title { vertical-output: true }

In [ ]:
#@title { vertical-output: true }